### ISSUE TITLE
Could you please tell me the theory behind the traj_generator2.m?

### ISSUE THREAD

**Issue by zhaowei19920524** [skylarcox/DroneSim#1]
Hi there,
I am very interested in your MATLAB simulation. But I have a small question:
Could you please tell me the theory behind the traj_generator2.m?
And could you please recommend some paper or books for it?
Thank you very much!
Wei Zhao

**Comment by skylarcox** [comment]
Hi Wei,

The code is based off of the class called "Aerial Robotics" by Vijay Kumar
on Coursera. It is available at:
https://www.coursera.org/learn/robotics-flight

-Skylar

**Comment by zhaowei19920524** [comment]
Thank you very much!
